### PR TITLE
HTTP.delete changed to HTTP.del

### PR DESCRIPTION
**Pull request by Alapan**

### CODE REVIEW

**Comment by brylie** [comment]
Please also increment the [`patch` version in `package.js`](https://github.com/apinf/meteor-api-umbrella/blob/master/package.js#L4) and publish the package on Atmosphere via `meteor publish`.

**Comment by brylie** [comment]
What is your Meteor.com username?

**Comment by Alapan** [comment]
It is alapan

**Comment by brylie** [comment]
Be sure to resolve conflicts. Just run `git pull origin develop`, and review the conflicting files.

**Comment by brylie** [comment]
The Github instructions for resolving conflicts are unnecessary.

**Comment by Alapan** [comment]
ok, I removed the 1.4.0 line

**Pull request merged**
